# serverless.yml
service: event-results-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, "development"}
  lambdaHashingVersion: 20201221

  environment:
    EVENT_RESULTS_TABLE: ${self:service}-${self:provider.stage}-eventResultsTable
    INFO_TABLE: ${self:service}-${self:provider.stage}-infoTable
    CACHE_BUCKET: ${self:service}-${self:provider.stage}-cache-bucket

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:QueryItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.EVENT_RESULTS_TABLE}"
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.INFO_TABLE}"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:provider.environment.CACHE_BUCKET}/*"


functions:
  setEventResults:
    handler: source/main.setEventResults
    events:
      - http:
          path: setEventResults/{eventKey}/divisionName/{divisionName}
          method: post
          cors: true
  getAllResults:
    handler: source/main.getAllResults
    events:
      - http:
          path: getAllResults
          method: get
          cors: true

resources:
  Resources:
    playerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.EVENT_RESULTS_TABLE}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: divisionName
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: divisionName
            KeyType: RANGE
    infoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.INFO_TABLE}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
    cacheBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:provider.environment.CACHE_BUCKET}
